language: go

go:
  - 1.17
  - tip

before_install:
  - go gÂ§et -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
