services:
  init:
    image: colonyos/colonies:v1.9.0
    volumes:
      - configuration:/configuration
      - ./init-entrypoint.sh:/init-entrypoint.sh
    command: ["/init-entrypoint.sh"]

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    hostname: timescaledb
    environment:
      POSTGRES_USER: colonies
      PGDATA: /var/lib/postgresql/data
      TZ: Europe/Stockholm
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - configuration:/configuration
      - ./timescaledb-entrypoint.sh:/timescaledb-entrypoint.sh
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: ["/bin/bash", "./timescaledb-entrypoint.sh"]

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: colonies
    volumes:
      - minio_data:/var/lib/minio/data
      - configuration:/configuration
      - ./minio-entrypoint.sh:/minio-entrypoint.sh
    depends_on:
      init:
        condition: service_completed_successfully
    entrypoint: ["/bin/sh", "minio-entrypoint.sh"]

  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1-1.24
    environment:
      COLONIES_DB_HOST: timescaledb
      COLONIES_DB_USER: colonies
      COLONIES_SERVER_TLS: false
      COLONIES_SERVER_PORT: 50080
      COLONIES_SERVER_HOST: localhost
      COLONIES_COLONY_NAME: dev
      MINIO_ROOT_USER: colonies
      AWS_S3_ENDPOINT: minio:9000
      AWS_S3_BUCKET: colonies-dev
      AWS_S3_TLS: false
      AWS_S3_SKIPVERIFY: false
      TZ: Europe/Stockholm
    volumes:
      - ../:/workspaces:cached
      - configuration:/configuration
    depends_on:
      - timescaledb
      - minio
    command: ["sleep", "infinity"]

volumes:
  timescaledb_data:
  configuration:
  minio_data:
